# apiVersion: v1
# kind: Pod
# metadata: 
#   name: test-job
# spec:
#   containers:
#   - name: long-job
#     image: python
#     command: ["python"]
#     args: ["-c", "import time; print('starting'); time.sleep(60); print('done')"]
#   restartPolicy : OnFailure # Always(default), Never, OnFailure

---

apiVersion: batch/v1
kind: Job
metadata: 
  name: test-job
spec: # Job
  template:
    spec: # Pod
      containers:
      - name: long-job
        image: python
        command: ["python"]
        args: ["-c", "import time; print('starting'); time.sleep(30); print('done')"]
      restartPolicy : Never # Always(default), Never, OnFailure
  backoffLimit: 2   # how many times kubernetes should restart on failure

  