
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awstut-webapp
spec:
  selector:
    matchLabels:
      component: webapp
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        component: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5-multi