apiVersion: apps/v1
kind: Deployment
metadata:
  name: awstut-ps
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ps
  template:
    metadata:
      labels:
        component: ps
    spec:
      containers:
      - name: awstut-ps
        image: richardchesterwood/k8s-fleetman-position-simulator:release1-multi
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

