apiVersion: apps/v1
kind: Deployment
metadata:
  name: awstut-pt
spec:
  selector:
    matchLabels:
      component: pt
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        component: pt
    spec:
      containers:
      - name: awstut-pt
        image: richardchesterwood/k8s-fleetman-position-tracker:release1-multi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice