apiVersion: apps/v1
kind: Deployment
metadata:
  name: awstut-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      component: queue
  template:
    metadata:
      labels:
        component: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1-multi

