apiVersion: v1
kind: Service
metadata:
  name: awstut-serice-queue
spec:
  type: NodePort
  selector:
    component: queue
  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
      nodePort: 30011